language: c
dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe'
install:
  sudo apt install make gcc-arm-none-eabi python3 binutils-arm-none-eabi
script:
  make -C bootloader/ && make -C keyboard/