PROJECT = keyboard

CFILES = $(wildcard *.c)
# AFILES += extra-asm.S

# Keep in sync with custom.devices.data
DEVICE=stm32f411ceu6_main_program

# Keep in sync with custom.devices.data and bootloader/main.c
DFUSE_ADDRESS=0x08004000

include ../common.mk