PROJECT = bootloader

CFILES = main.c
# CFILES += extra.c
# AFILES += extra-asm.S
CSTD = -std=gnu99

DEVICE=stm32f411ceu6

# Keep in sync with custom.devices.data and bootloader/main.c
DFUSE_ADDRESS=0x08000000

include ../common.mk